import os.path
import json
import numpy as np

# Extract numeric features from an Essentia audio feature report.
# Save them as a numpy array of floats.

# These are the features we use and this is the order we use them in.
# We save an .npy file for each track in the library containing these values
# in this order, so don't change it lightly, and if you do, find some way to
# make the check() method fail. (Perhaps we ought to have a version feature.)
# Currently unused:
#   lowlevel.barkbands
#   lowlevel.erbbands
#   lowlevel.melbands
#   lowlevel.melbands128
#   lowlevel.mfcc.cov
#   lowlevel.mfcc.icov
#   lowlevel.gfcc.cov
#   lowlevel.gfcc.icov
#   rhythm.bpm_histogram

_feature_paths = [
    ('lowlevel', 'average_loudness'),
    ('lowlevel', 'barkbands_crest', 'min'),
    ('lowlevel', 'barkbands_crest', 'max'),
    ('lowlevel', 'barkbands_crest', 'median'),
    ('lowlevel', 'barkbands_crest', 'mean'),
    ('lowlevel', 'barkbands_crest', 'var'),
    ('lowlevel', 'barkbands_crest', 'stdev'),
    ('lowlevel', 'barkbands_crest', 'dmean'),
    ('lowlevel', 'barkbands_crest', 'dvar'),
    ('lowlevel', 'barkbands_crest', 'dmean2'),
    ('lowlevel', 'barkbands_crest', 'dvar2'),
    ('lowlevel', 'barkbands_flatness_db', 'min'),
    ('lowlevel', 'barkbands_flatness_db', 'max'),
    ('lowlevel', 'barkbands_flatness_db', 'median'),
    ('lowlevel', 'barkbands_flatness_db', 'mean'),
    ('lowlevel', 'barkbands_flatness_db', 'var'),
    ('lowlevel', 'barkbands_flatness_db', 'stdev'),
    ('lowlevel', 'barkbands_flatness_db', 'dmean'),
    ('lowlevel', 'barkbands_flatness_db', 'dvar'),
    ('lowlevel', 'barkbands_flatness_db', 'dmean2'),
    ('lowlevel', 'barkbands_flatness_db', 'dvar2'),
    ('lowlevel', 'barkbands_kurtosis', 'min'),
    ('lowlevel', 'barkbands_kurtosis', 'max'),
    ('lowlevel', 'barkbands_kurtosis', 'median'),
    ('lowlevel', 'barkbands_kurtosis', 'mean'),
    ('lowlevel', 'barkbands_kurtosis', 'var'),
    ('lowlevel', 'barkbands_kurtosis', 'stdev'),
    ('lowlevel', 'barkbands_kurtosis', 'dmean'),
    ('lowlevel', 'barkbands_kurtosis', 'dvar'),
    ('lowlevel', 'barkbands_kurtosis', 'dmean2'),
    ('lowlevel', 'barkbands_kurtosis', 'dvar2'),
    ('lowlevel', 'barkbands_skewness', 'min'),
    ('lowlevel', 'barkbands_skewness', 'max'),
    ('lowlevel', 'barkbands_skewness', 'median'),
    ('lowlevel', 'barkbands_skewness', 'mean'),
    ('lowlevel', 'barkbands_skewness', 'var'),
    ('lowlevel', 'barkbands_skewness', 'stdev'),
    ('lowlevel', 'barkbands_skewness', 'dmean'),
    ('lowlevel', 'barkbands_skewness', 'dvar'),
    ('lowlevel', 'barkbands_skewness', 'dmean2'),
    ('lowlevel', 'barkbands_skewness', 'dvar2'),
    ('lowlevel', 'barkbands_spread', 'min'),
    ('lowlevel', 'barkbands_spread', 'max'),
    ('lowlevel', 'barkbands_spread', 'median'),
    ('lowlevel', 'barkbands_spread', 'mean'),
    ('lowlevel', 'barkbands_spread', 'var'),
    ('lowlevel', 'barkbands_spread', 'stdev'),
    ('lowlevel', 'barkbands_spread', 'dmean'),
    ('lowlevel', 'barkbands_spread', 'dvar'),
    ('lowlevel', 'barkbands_spread', 'dmean2'),
    ('lowlevel', 'barkbands_spread', 'dvar2'),
    ('lowlevel', 'dissonance', 'min'),
    ('lowlevel', 'dissonance', 'max'),
    ('lowlevel', 'dissonance', 'median'),
    ('lowlevel', 'dissonance', 'mean'),
    ('lowlevel', 'dissonance', 'var'),
    ('lowlevel', 'dissonance', 'stdev'),
    ('lowlevel', 'dissonance', 'dmean'),
    ('lowlevel', 'dissonance', 'dvar'),
    ('lowlevel', 'dissonance', 'dmean2'),
    ('lowlevel', 'dissonance', 'dvar2'),
    ('lowlevel', 'dynamic_complexity'),
    ('lowlevel', 'erbbands_crest', 'min'),
    ('lowlevel', 'erbbands_crest', 'max'),
    ('lowlevel', 'erbbands_crest', 'median'),
    ('lowlevel', 'erbbands_crest', 'mean'),
    ('lowlevel', 'erbbands_crest', 'var'),
    ('lowlevel', 'erbbands_crest', 'stdev'),
    ('lowlevel', 'erbbands_crest', 'dmean'),
    ('lowlevel', 'erbbands_crest', 'dvar'),
    ('lowlevel', 'erbbands_crest', 'dmean2'),
    ('lowlevel', 'erbbands_crest', 'dvar2'),
    ('lowlevel', 'erbbands_flatness_db', 'min'),
    ('lowlevel', 'erbbands_flatness_db', 'max'),
    ('lowlevel', 'erbbands_flatness_db', 'median'),
    ('lowlevel', 'erbbands_flatness_db', 'mean'),
    ('lowlevel', 'erbbands_flatness_db', 'var'),
    ('lowlevel', 'erbbands_flatness_db', 'stdev'),
    ('lowlevel', 'erbbands_flatness_db', 'dmean'),
    ('lowlevel', 'erbbands_flatness_db', 'dvar'),
    ('lowlevel', 'erbbands_flatness_db', 'dmean2'),
    ('lowlevel', 'erbbands_flatness_db', 'dvar2'),
    ('lowlevel', 'erbbands_kurtosis', 'min'),
    ('lowlevel', 'erbbands_kurtosis', 'max'),
    ('lowlevel', 'erbbands_kurtosis', 'median'),
    ('lowlevel', 'erbbands_kurtosis', 'mean'),
    ('lowlevel', 'erbbands_kurtosis', 'var'),
    ('lowlevel', 'erbbands_kurtosis', 'stdev'),
    ('lowlevel', 'erbbands_kurtosis', 'dmean'),
    ('lowlevel', 'erbbands_kurtosis', 'dvar'),
    ('lowlevel', 'erbbands_kurtosis', 'dmean2'),
    ('lowlevel', 'erbbands_kurtosis', 'dvar2'),
    ('lowlevel', 'erbbands_skewness', 'min'),
    ('lowlevel', 'erbbands_skewness', 'max'),
    ('lowlevel', 'erbbands_skewness', 'median'),
    ('lowlevel', 'erbbands_skewness', 'mean'),
    ('lowlevel', 'erbbands_skewness', 'var'),
    ('lowlevel', 'erbbands_skewness', 'stdev'),
    ('lowlevel', 'erbbands_skewness', 'dmean'),
    ('lowlevel', 'erbbands_skewness', 'dvar'),
    ('lowlevel', 'erbbands_skewness', 'dmean2'),
    ('lowlevel', 'erbbands_skewness', 'dvar2'),
    ('lowlevel', 'erbbands_spread', 'min'),
    ('lowlevel', 'erbbands_spread', 'max'),
    ('lowlevel', 'erbbands_spread', 'median'),
    ('lowlevel', 'erbbands_spread', 'mean'),
    ('lowlevel', 'erbbands_spread', 'var'),
    ('lowlevel', 'erbbands_spread', 'stdev'),
    ('lowlevel', 'erbbands_spread', 'dmean'),
    ('lowlevel', 'erbbands_spread', 'dvar'),
    ('lowlevel', 'erbbands_spread', 'dmean2'),
    ('lowlevel', 'erbbands_spread', 'dvar2'),
    ('lowlevel', 'hfc', 'min'),
    ('lowlevel', 'hfc', 'max'),
    ('lowlevel', 'hfc', 'median'),
    ('lowlevel', 'hfc', 'mean'),
    ('lowlevel', 'hfc', 'var'),
    ('lowlevel', 'hfc', 'stdev'),
    ('lowlevel', 'hfc', 'dmean'),
    ('lowlevel', 'hfc', 'dvar'),
    ('lowlevel', 'hfc', 'dmean2'),
    ('lowlevel', 'hfc', 'dvar2'),
    ('lowlevel', 'loudness_ebu128', 'integrated'),
    ('lowlevel', 'loudness_ebu128', 'loudness_range'),
    ('lowlevel', 'loudness_ebu128', 'momentary', 'min'),
    ('lowlevel', 'loudness_ebu128', 'momentary', 'max'),
    ('lowlevel', 'loudness_ebu128', 'momentary', 'median'),
    ('lowlevel', 'loudness_ebu128', 'momentary', 'mean'),
    ('lowlevel', 'loudness_ebu128', 'momentary', 'var'),
    ('lowlevel', 'loudness_ebu128', 'momentary', 'stdev'),
    ('lowlevel', 'loudness_ebu128', 'momentary', 'dmean'),
    ('lowlevel', 'loudness_ebu128', 'momentary', 'dvar'),
    ('lowlevel', 'loudness_ebu128', 'momentary', 'dmean2'),
    ('lowlevel', 'loudness_ebu128', 'momentary', 'dvar2'),
    ('lowlevel', 'loudness_ebu128', 'short_term', 'min'),
    ('lowlevel', 'loudness_ebu128', 'short_term', 'max'),
    ('lowlevel', 'loudness_ebu128', 'short_term', 'median'),
    ('lowlevel', 'loudness_ebu128', 'short_term', 'mean'),
    ('lowlevel', 'loudness_ebu128', 'short_term', 'var'),
    ('lowlevel', 'loudness_ebu128', 'short_term', 'stdev'),
    ('lowlevel', 'loudness_ebu128', 'short_term', 'dmean'),
    ('lowlevel', 'loudness_ebu128', 'short_term', 'dvar'),
    ('lowlevel', 'loudness_ebu128', 'short_term', 'dmean2'),
    ('lowlevel', 'loudness_ebu128', 'short_term', 'dvar2'),
    ('lowlevel', 'melbands_crest', 'min'),
    ('lowlevel', 'melbands_crest', 'max'),
    ('lowlevel', 'melbands_crest', 'median'),
    ('lowlevel', 'melbands_crest', 'mean'),
    ('lowlevel', 'melbands_crest', 'var'),
    ('lowlevel', 'melbands_crest', 'stdev'),
    ('lowlevel', 'melbands_crest', 'dmean'),
    ('lowlevel', 'melbands_crest', 'dvar'),
    ('lowlevel', 'melbands_crest', 'dmean2'),
    ('lowlevel', 'melbands_crest', 'dvar2'),
    ('lowlevel', 'melbands_flatness_db', 'min'),
    ('lowlevel', 'melbands_flatness_db', 'max'),
    ('lowlevel', 'melbands_flatness_db', 'median'),
    ('lowlevel', 'melbands_flatness_db', 'mean'),
    ('lowlevel', 'melbands_flatness_db', 'var'),
    ('lowlevel', 'melbands_flatness_db', 'stdev'),
    ('lowlevel', 'melbands_flatness_db', 'dmean'),
    ('lowlevel', 'melbands_flatness_db', 'dvar'),
    ('lowlevel', 'melbands_flatness_db', 'dmean2'),
    ('lowlevel', 'melbands_flatness_db', 'dvar2'),
    ('lowlevel', 'melbands_kurtosis', 'min'),
    ('lowlevel', 'melbands_kurtosis', 'max'),
    ('lowlevel', 'melbands_kurtosis', 'median'),
    ('lowlevel', 'melbands_kurtosis', 'mean'),
    ('lowlevel', 'melbands_kurtosis', 'var'),
    ('lowlevel', 'melbands_kurtosis', 'stdev'),
    ('lowlevel', 'melbands_kurtosis', 'dmean'),
    ('lowlevel', 'melbands_kurtosis', 'dvar'),
    ('lowlevel', 'melbands_kurtosis', 'dmean2'),
    ('lowlevel', 'melbands_kurtosis', 'dvar2'),
    ('lowlevel', 'melbands_skewness', 'min'),
    ('lowlevel', 'melbands_skewness', 'max'),
    ('lowlevel', 'melbands_skewness', 'median'),
    ('lowlevel', 'melbands_skewness', 'mean'),
    ('lowlevel', 'melbands_skewness', 'var'),
    ('lowlevel', 'melbands_skewness', 'stdev'),
    ('lowlevel', 'melbands_skewness', 'dmean'),
    ('lowlevel', 'melbands_skewness', 'dvar'),
    ('lowlevel', 'melbands_skewness', 'dmean2'),
    ('lowlevel', 'melbands_skewness', 'dvar2'),
    ('lowlevel', 'melbands_spread', 'min'),
    ('lowlevel', 'melbands_spread', 'max'),
    ('lowlevel', 'melbands_spread', 'median'),
    ('lowlevel', 'melbands_spread', 'mean'),
    ('lowlevel', 'melbands_spread', 'var'),
    ('lowlevel', 'melbands_spread', 'stdev'),
    ('lowlevel', 'melbands_spread', 'dmean'),
    ('lowlevel', 'melbands_spread', 'dvar'),
    ('lowlevel', 'melbands_spread', 'dmean2'),
    ('lowlevel', 'melbands_spread', 'dvar2'),
    ('lowlevel', 'pitch_salience', 'min'),
    ('lowlevel', 'pitch_salience', 'max'),
    ('lowlevel', 'pitch_salience', 'median'),
    ('lowlevel', 'pitch_salience', 'mean'),
    ('lowlevel', 'pitch_salience', 'var'),
    ('lowlevel', 'pitch_salience', 'stdev'),
    ('lowlevel', 'pitch_salience', 'dmean'),
    ('lowlevel', 'pitch_salience', 'dvar'),
    ('lowlevel', 'pitch_salience', 'dmean2'),
    ('lowlevel', 'pitch_salience', 'dvar2'),
    ('lowlevel', 'silence_rate_20dB', 'min'),
    ('lowlevel', 'silence_rate_20dB', 'max'),
    ('lowlevel', 'silence_rate_20dB', 'median'),
    ('lowlevel', 'silence_rate_20dB', 'mean'),
    ('lowlevel', 'silence_rate_20dB', 'var'),
    ('lowlevel', 'silence_rate_20dB', 'stdev'),
    ('lowlevel', 'silence_rate_20dB', 'dmean'),
    ('lowlevel', 'silence_rate_20dB', 'dvar'),
    ('lowlevel', 'silence_rate_20dB', 'dmean2'),
    ('lowlevel', 'silence_rate_20dB', 'dvar2'),
    ('lowlevel', 'silence_rate_30dB', 'min'),
    ('lowlevel', 'silence_rate_30dB', 'max'),
    ('lowlevel', 'silence_rate_30dB', 'median'),
    ('lowlevel', 'silence_rate_30dB', 'mean'),
    ('lowlevel', 'silence_rate_30dB', 'var'),
    ('lowlevel', 'silence_rate_30dB', 'stdev'),
    ('lowlevel', 'silence_rate_30dB', 'dmean'),
    ('lowlevel', 'silence_rate_30dB', 'dvar'),
    ('lowlevel', 'silence_rate_30dB', 'dmean2'),
    ('lowlevel', 'silence_rate_30dB', 'dvar2'),
    ('lowlevel', 'silence_rate_60dB', 'min'),
    ('lowlevel', 'silence_rate_60dB', 'max'),
    ('lowlevel', 'silence_rate_60dB', 'median'),
    ('lowlevel', 'silence_rate_60dB', 'mean'),
    ('lowlevel', 'silence_rate_60dB', 'var'),
    ('lowlevel', 'silence_rate_60dB', 'stdev'),
    ('lowlevel', 'silence_rate_60dB', 'dmean'),
    ('lowlevel', 'silence_rate_60dB', 'dvar'),
    ('lowlevel', 'silence_rate_60dB', 'dmean2'),
    ('lowlevel', 'silence_rate_60dB', 'dvar2'),
    ('lowlevel', 'spectral_centroid', 'min'),
    ('lowlevel', 'spectral_centroid', 'max'),
    ('lowlevel', 'spectral_centroid', 'median'),
    ('lowlevel', 'spectral_centroid', 'mean'),
    ('lowlevel', 'spectral_centroid', 'var'),
    ('lowlevel', 'spectral_centroid', 'stdev'),
    ('lowlevel', 'spectral_centroid', 'dmean'),
    ('lowlevel', 'spectral_centroid', 'dvar'),
    ('lowlevel', 'spectral_centroid', 'dmean2'),
    ('lowlevel', 'spectral_centroid', 'dvar2'),
    ('lowlevel', 'spectral_complexity', 'min'),
    ('lowlevel', 'spectral_complexity', 'max'),
    ('lowlevel', 'spectral_complexity', 'median'),
    ('lowlevel', 'spectral_complexity', 'mean'),
    ('lowlevel', 'spectral_complexity', 'var'),
    ('lowlevel', 'spectral_complexity', 'stdev'),
    ('lowlevel', 'spectral_complexity', 'dmean'),
    ('lowlevel', 'spectral_complexity', 'dvar'),
    ('lowlevel', 'spectral_complexity', 'dmean2'),
    ('lowlevel', 'spectral_complexity', 'dvar2'),
    ('lowlevel', 'spectral_contrast_coeffs', 'min', 0),
    ('lowlevel', 'spectral_contrast_coeffs', 'min', 1),
    ('lowlevel', 'spectral_contrast_coeffs', 'min', 2),
    ('lowlevel', 'spectral_contrast_coeffs', 'min', 3),
    ('lowlevel', 'spectral_contrast_coeffs', 'min', 4),
    ('lowlevel', 'spectral_contrast_coeffs', 'min', 5),
    ('lowlevel', 'spectral_contrast_coeffs', 'max', 0),
    ('lowlevel', 'spectral_contrast_coeffs', 'max', 1),
    ('lowlevel', 'spectral_contrast_coeffs', 'max', 2),
    ('lowlevel', 'spectral_contrast_coeffs', 'max', 3),
    ('lowlevel', 'spectral_contrast_coeffs', 'max', 4),
    ('lowlevel', 'spectral_contrast_coeffs', 'max', 5),
    ('lowlevel', 'spectral_contrast_coeffs', 'median', 0),
    ('lowlevel', 'spectral_contrast_coeffs', 'median', 1),
    ('lowlevel', 'spectral_contrast_coeffs', 'median', 2),
    ('lowlevel', 'spectral_contrast_coeffs', 'median', 3),
    ('lowlevel', 'spectral_contrast_coeffs', 'median', 4),
    ('lowlevel', 'spectral_contrast_coeffs', 'median', 5),
    ('lowlevel', 'spectral_contrast_coeffs', 'mean', 0),
    ('lowlevel', 'spectral_contrast_coeffs', 'mean', 1),
    ('lowlevel', 'spectral_contrast_coeffs', 'mean', 2),
    ('lowlevel', 'spectral_contrast_coeffs', 'mean', 3),
    ('lowlevel', 'spectral_contrast_coeffs', 'mean', 4),
    ('lowlevel', 'spectral_contrast_coeffs', 'mean', 5),
    ('lowlevel', 'spectral_contrast_coeffs', 'var', 0),
    ('lowlevel', 'spectral_contrast_coeffs', 'var', 1),
    ('lowlevel', 'spectral_contrast_coeffs', 'var', 2),
    ('lowlevel', 'spectral_contrast_coeffs', 'var', 3),
    ('lowlevel', 'spectral_contrast_coeffs', 'var', 4),
    ('lowlevel', 'spectral_contrast_coeffs', 'var', 5),
    ('lowlevel', 'spectral_contrast_coeffs', 'stdev', 0),
    ('lowlevel', 'spectral_contrast_coeffs', 'stdev', 1),
    ('lowlevel', 'spectral_contrast_coeffs', 'stdev', 2),
    ('lowlevel', 'spectral_contrast_coeffs', 'stdev', 3),
    ('lowlevel', 'spectral_contrast_coeffs', 'stdev', 4),
    ('lowlevel', 'spectral_contrast_coeffs', 'stdev', 5),
    ('lowlevel', 'spectral_contrast_coeffs', 'dmean', 0),
    ('lowlevel', 'spectral_contrast_coeffs', 'dmean', 1),
    ('lowlevel', 'spectral_contrast_coeffs', 'dmean', 2),
    ('lowlevel', 'spectral_contrast_coeffs', 'dmean', 3),
    ('lowlevel', 'spectral_contrast_coeffs', 'dmean', 4),
    ('lowlevel', 'spectral_contrast_coeffs', 'dmean', 5),
    ('lowlevel', 'spectral_contrast_coeffs', 'dvar', 0),
    ('lowlevel', 'spectral_contrast_coeffs', 'dvar', 1),
    ('lowlevel', 'spectral_contrast_coeffs', 'dvar', 2),
    ('lowlevel', 'spectral_contrast_coeffs', 'dvar', 3),
    ('lowlevel', 'spectral_contrast_coeffs', 'dvar', 4),
    ('lowlevel', 'spectral_contrast_coeffs', 'dvar', 5),
    ('lowlevel', 'spectral_contrast_coeffs', 'dmean2', 0),
    ('lowlevel', 'spectral_contrast_coeffs', 'dmean2', 1),
    ('lowlevel', 'spectral_contrast_coeffs', 'dmean2', 2),
    ('lowlevel', 'spectral_contrast_coeffs', 'dmean2', 3),
    ('lowlevel', 'spectral_contrast_coeffs', 'dmean2', 4),
    ('lowlevel', 'spectral_contrast_coeffs', 'dmean2', 5),
    ('lowlevel', 'spectral_contrast_coeffs', 'dvar2', 0),
    ('lowlevel', 'spectral_contrast_coeffs', 'dvar2', 1),
    ('lowlevel', 'spectral_contrast_coeffs', 'dvar2', 2),
    ('lowlevel', 'spectral_contrast_coeffs', 'dvar2', 3),
    ('lowlevel', 'spectral_contrast_coeffs', 'dvar2', 4),
    ('lowlevel', 'spectral_contrast_coeffs', 'dvar2', 5),
    ('lowlevel', 'spectral_contrast_valleys', 'min', 0),
    ('lowlevel', 'spectral_contrast_valleys', 'min', 1),
    ('lowlevel', 'spectral_contrast_valleys', 'min', 2),
    ('lowlevel', 'spectral_contrast_valleys', 'min', 3),
    ('lowlevel', 'spectral_contrast_valleys', 'min', 4),
    ('lowlevel', 'spectral_contrast_valleys', 'min', 5),
    ('lowlevel', 'spectral_contrast_valleys', 'max', 0),
    ('lowlevel', 'spectral_contrast_valleys', 'max', 1),
    ('lowlevel', 'spectral_contrast_valleys', 'max', 2),
    ('lowlevel', 'spectral_contrast_valleys', 'max', 3),
    ('lowlevel', 'spectral_contrast_valleys', 'max', 4),
    ('lowlevel', 'spectral_contrast_valleys', 'max', 5),
    ('lowlevel', 'spectral_contrast_valleys', 'median', 0),
    ('lowlevel', 'spectral_contrast_valleys', 'median', 1),
    ('lowlevel', 'spectral_contrast_valleys', 'median', 2),
    ('lowlevel', 'spectral_contrast_valleys', 'median', 3),
    ('lowlevel', 'spectral_contrast_valleys', 'median', 4),
    ('lowlevel', 'spectral_contrast_valleys', 'median', 5),
    ('lowlevel', 'spectral_contrast_valleys', 'mean', 0),
    ('lowlevel', 'spectral_contrast_valleys', 'mean', 1),
    ('lowlevel', 'spectral_contrast_valleys', 'mean', 2),
    ('lowlevel', 'spectral_contrast_valleys', 'mean', 3),
    ('lowlevel', 'spectral_contrast_valleys', 'mean', 4),
    ('lowlevel', 'spectral_contrast_valleys', 'mean', 5),
    ('lowlevel', 'spectral_contrast_valleys', 'var', 0),
    ('lowlevel', 'spectral_contrast_valleys', 'var', 1),
    ('lowlevel', 'spectral_contrast_valleys', 'var', 2),
    ('lowlevel', 'spectral_contrast_valleys', 'var', 3),
    ('lowlevel', 'spectral_contrast_valleys', 'var', 4),
    ('lowlevel', 'spectral_contrast_valleys', 'var', 5),
    ('lowlevel', 'spectral_contrast_valleys', 'stdev', 0),
    ('lowlevel', 'spectral_contrast_valleys', 'stdev', 1),
    ('lowlevel', 'spectral_contrast_valleys', 'stdev', 2),
    ('lowlevel', 'spectral_contrast_valleys', 'stdev', 3),
    ('lowlevel', 'spectral_contrast_valleys', 'stdev', 4),
    ('lowlevel', 'spectral_contrast_valleys', 'stdev', 5),
    ('lowlevel', 'spectral_contrast_valleys', 'dmean', 0),
    ('lowlevel', 'spectral_contrast_valleys', 'dmean', 1),
    ('lowlevel', 'spectral_contrast_valleys', 'dmean', 2),
    ('lowlevel', 'spectral_contrast_valleys', 'dmean', 3),
    ('lowlevel', 'spectral_contrast_valleys', 'dmean', 4),
    ('lowlevel', 'spectral_contrast_valleys', 'dmean', 5),
    ('lowlevel', 'spectral_contrast_valleys', 'dvar', 0),
    ('lowlevel', 'spectral_contrast_valleys', 'dvar', 1),
    ('lowlevel', 'spectral_contrast_valleys', 'dvar', 2),
    ('lowlevel', 'spectral_contrast_valleys', 'dvar', 3),
    ('lowlevel', 'spectral_contrast_valleys', 'dvar', 4),
    ('lowlevel', 'spectral_contrast_valleys', 'dvar', 5),
    ('lowlevel', 'spectral_contrast_valleys', 'dmean2', 0),
    ('lowlevel', 'spectral_contrast_valleys', 'dmean2', 1),
    ('lowlevel', 'spectral_contrast_valleys', 'dmean2', 2),
    ('lowlevel', 'spectral_contrast_valleys', 'dmean2', 3),
    ('lowlevel', 'spectral_contrast_valleys', 'dmean2', 4),
    ('lowlevel', 'spectral_contrast_valleys', 'dmean2', 5),
    ('lowlevel', 'spectral_contrast_valleys', 'dvar2', 0),
    ('lowlevel', 'spectral_contrast_valleys', 'dvar2', 1),
    ('lowlevel', 'spectral_contrast_valleys', 'dvar2', 2),
    ('lowlevel', 'spectral_contrast_valleys', 'dvar2', 3),
    ('lowlevel', 'spectral_contrast_valleys', 'dvar2', 4),
    ('lowlevel', 'spectral_contrast_valleys', 'dvar2', 5),
    ('lowlevel', 'spectral_decrease', 'min'),
    ('lowlevel', 'spectral_decrease', 'max'),
    ('lowlevel', 'spectral_decrease', 'median'),
    ('lowlevel', 'spectral_decrease', 'mean'),
    ('lowlevel', 'spectral_decrease', 'var'),
    ('lowlevel', 'spectral_decrease', 'stdev'),
    ('lowlevel', 'spectral_decrease', 'dmean'),
    ('lowlevel', 'spectral_decrease', 'dvar'),
    ('lowlevel', 'spectral_decrease', 'dmean2'),
    ('lowlevel', 'spectral_decrease', 'dvar2'),
    ('lowlevel', 'spectral_energy', 'min'),
    ('lowlevel', 'spectral_energy', 'max'),
    ('lowlevel', 'spectral_energy', 'median'),
    ('lowlevel', 'spectral_energy', 'mean'),
    ('lowlevel', 'spectral_energy', 'var'),
    ('lowlevel', 'spectral_energy', 'stdev'),
    ('lowlevel', 'spectral_energy', 'dmean'),
    ('lowlevel', 'spectral_energy', 'dvar'),
    ('lowlevel', 'spectral_energy', 'dmean2'),
    ('lowlevel', 'spectral_energy', 'dvar2'),
    ('lowlevel', 'spectral_energyband_high', 'min'),
    ('lowlevel', 'spectral_energyband_high', 'max'),
    ('lowlevel', 'spectral_energyband_high', 'median'),
    ('lowlevel', 'spectral_energyband_high', 'mean'),
    ('lowlevel', 'spectral_energyband_high', 'var'),
    ('lowlevel', 'spectral_energyband_high', 'stdev'),
    ('lowlevel', 'spectral_energyband_high', 'dmean'),
    ('lowlevel', 'spectral_energyband_high', 'dvar'),
    ('lowlevel', 'spectral_energyband_high', 'dmean2'),
    ('lowlevel', 'spectral_energyband_high', 'dvar2'),
    ('lowlevel', 'spectral_energyband_low', 'min'),
    ('lowlevel', 'spectral_energyband_low', 'max'),
    ('lowlevel', 'spectral_energyband_low', 'median'),
    ('lowlevel', 'spectral_energyband_low', 'mean'),
    ('lowlevel', 'spectral_energyband_low', 'var'),
    ('lowlevel', 'spectral_energyband_low', 'stdev'),
    ('lowlevel', 'spectral_energyband_low', 'dmean'),
    ('lowlevel', 'spectral_energyband_low', 'dvar'),
    ('lowlevel', 'spectral_energyband_low', 'dmean2'),
    ('lowlevel', 'spectral_energyband_low', 'dvar2'),
    ('lowlevel', 'spectral_energyband_middle_high', 'min'),
    ('lowlevel', 'spectral_energyband_middle_high', 'max'),
    ('lowlevel', 'spectral_energyband_middle_high', 'median'),
    ('lowlevel', 'spectral_energyband_middle_high', 'mean'),
    ('lowlevel', 'spectral_energyband_middle_high', 'var'),
    ('lowlevel', 'spectral_energyband_middle_high', 'stdev'),
    ('lowlevel', 'spectral_energyband_middle_high', 'dmean'),
    ('lowlevel', 'spectral_energyband_middle_high', 'dvar'),
    ('lowlevel', 'spectral_energyband_middle_high', 'dmean2'),
    ('lowlevel', 'spectral_energyband_middle_high', 'dvar2'),
    ('lowlevel', 'spectral_energyband_middle_low', 'min'),
    ('lowlevel', 'spectral_energyband_middle_low', 'max'),
    ('lowlevel', 'spectral_energyband_middle_low', 'median'),
    ('lowlevel', 'spectral_energyband_middle_low', 'mean'),
    ('lowlevel', 'spectral_energyband_middle_low', 'var'),
    ('lowlevel', 'spectral_energyband_middle_low', 'stdev'),
    ('lowlevel', 'spectral_energyband_middle_low', 'dmean'),
    ('lowlevel', 'spectral_energyband_middle_low', 'dvar'),
    ('lowlevel', 'spectral_energyband_middle_low', 'dmean2'),
    ('lowlevel', 'spectral_energyband_middle_low', 'dvar2'),
    ('lowlevel', 'spectral_entropy', 'min'),
    ('lowlevel', 'spectral_entropy', 'max'),
    ('lowlevel', 'spectral_entropy', 'median'),
    ('lowlevel', 'spectral_entropy', 'mean'),
    ('lowlevel', 'spectral_entropy', 'var'),
    ('lowlevel', 'spectral_entropy', 'stdev'),
    ('lowlevel', 'spectral_entropy', 'dmean'),
    ('lowlevel', 'spectral_entropy', 'dvar'),
    ('lowlevel', 'spectral_entropy', 'dmean2'),
    ('lowlevel', 'spectral_entropy', 'dvar2'),
    ('lowlevel', 'spectral_flux', 'min'),
    ('lowlevel', 'spectral_flux', 'max'),
    ('lowlevel', 'spectral_flux', 'median'),
    ('lowlevel', 'spectral_flux', 'mean'),
    ('lowlevel', 'spectral_flux', 'var'),
    ('lowlevel', 'spectral_flux', 'stdev'),
    ('lowlevel', 'spectral_flux', 'dmean'),
    ('lowlevel', 'spectral_flux', 'dvar'),
    ('lowlevel', 'spectral_flux', 'dmean2'),
    ('lowlevel', 'spectral_flux', 'dvar2'),
    ('lowlevel', 'spectral_kurtosis', 'min'),
    ('lowlevel', 'spectral_kurtosis', 'max'),
    ('lowlevel', 'spectral_kurtosis', 'median'),
    ('lowlevel', 'spectral_kurtosis', 'mean'),
    ('lowlevel', 'spectral_kurtosis', 'var'),
    ('lowlevel', 'spectral_kurtosis', 'stdev'),
    ('lowlevel', 'spectral_kurtosis', 'dmean'),
    ('lowlevel', 'spectral_kurtosis', 'dvar'),
    ('lowlevel', 'spectral_kurtosis', 'dmean2'),
    ('lowlevel', 'spectral_kurtosis', 'dvar2'),
    ('lowlevel', 'spectral_rms', 'min'),
    ('lowlevel', 'spectral_rms', 'max'),
    ('lowlevel', 'spectral_rms', 'median'),
    ('lowlevel', 'spectral_rms', 'mean'),
    ('lowlevel', 'spectral_rms', 'var'),
    ('lowlevel', 'spectral_rms', 'stdev'),
    ('lowlevel', 'spectral_rms', 'dmean'),
    ('lowlevel', 'spectral_rms', 'dvar'),
    ('lowlevel', 'spectral_rms', 'dmean2'),
    ('lowlevel', 'spectral_rms', 'dvar2'),
    ('lowlevel', 'spectral_rolloff', 'min'),
    ('lowlevel', 'spectral_rolloff', 'max'),
    ('lowlevel', 'spectral_rolloff', 'median'),
    ('lowlevel', 'spectral_rolloff', 'mean'),
    ('lowlevel', 'spectral_rolloff', 'var'),
    ('lowlevel', 'spectral_rolloff', 'stdev'),
    ('lowlevel', 'spectral_rolloff', 'dmean'),
    ('lowlevel', 'spectral_rolloff', 'dvar'),
    ('lowlevel', 'spectral_rolloff', 'dmean2'),
    ('lowlevel', 'spectral_rolloff', 'dvar2'),
    ('lowlevel', 'spectral_skewness', 'min'),
    ('lowlevel', 'spectral_skewness', 'max'),
    ('lowlevel', 'spectral_skewness', 'median'),
    ('lowlevel', 'spectral_skewness', 'mean'),
    ('lowlevel', 'spectral_skewness', 'var'),
    ('lowlevel', 'spectral_skewness', 'stdev'),
    ('lowlevel', 'spectral_skewness', 'dmean'),
    ('lowlevel', 'spectral_skewness', 'dvar'),
    ('lowlevel', 'spectral_skewness', 'dmean2'),
    ('lowlevel', 'spectral_skewness', 'dvar2'),
    ('lowlevel', 'spectral_spread', 'min'),
    ('lowlevel', 'spectral_spread', 'max'),
    ('lowlevel', 'spectral_spread', 'median'),
    ('lowlevel', 'spectral_spread', 'mean'),
    ('lowlevel', 'spectral_spread', 'var'),
    ('lowlevel', 'spectral_spread', 'stdev'),
    ('lowlevel', 'spectral_spread', 'dmean'),
    ('lowlevel', 'spectral_spread', 'dvar'),
    ('lowlevel', 'spectral_spread', 'dmean2'),
    ('lowlevel', 'spectral_spread', 'dvar2'),
    ('lowlevel', 'spectral_strongpeak', 'min'),
    ('lowlevel', 'spectral_strongpeak', 'max'),
    ('lowlevel', 'spectral_strongpeak', 'median'),
    ('lowlevel', 'spectral_strongpeak', 'mean'),
    ('lowlevel', 'spectral_strongpeak', 'var'),
    ('lowlevel', 'spectral_strongpeak', 'stdev'),
    ('lowlevel', 'spectral_strongpeak', 'dmean'),
    ('lowlevel', 'spectral_strongpeak', 'dvar'),
    ('lowlevel', 'spectral_strongpeak', 'dmean2'),
    ('lowlevel', 'spectral_strongpeak', 'dvar2'),
    ('lowlevel', 'zerocrossingrate', 'min'),
    ('lowlevel', 'zerocrossingrate', 'max'),
    ('lowlevel', 'zerocrossingrate', 'median'),
    ('lowlevel', 'zerocrossingrate', 'mean'),
    ('lowlevel', 'zerocrossingrate', 'var'),
    ('lowlevel', 'zerocrossingrate', 'stdev'),
    ('lowlevel', 'zerocrossingrate', 'dmean'),
    ('lowlevel', 'zerocrossingrate', 'dvar'),
    ('lowlevel', 'zerocrossingrate', 'dmean2'),
    ('lowlevel', 'zerocrossingrate', 'dvar2'),
    ('lowlevel', 'gfcc', 'mean', 0),
    ('lowlevel', 'gfcc', 'mean', 1),
    ('lowlevel', 'gfcc', 'mean', 2),
    ('lowlevel', 'gfcc', 'mean', 3),
    ('lowlevel', 'gfcc', 'mean', 4),
    ('lowlevel', 'gfcc', 'mean', 5),
    ('lowlevel', 'gfcc', 'mean', 6),
    ('lowlevel', 'gfcc', 'mean', 7),
    ('lowlevel', 'gfcc', 'mean', 8),
    ('lowlevel', 'gfcc', 'mean', 9),
    ('lowlevel', 'gfcc', 'mean', 10),
    ('lowlevel', 'gfcc', 'mean', 11),
    ('lowlevel', 'gfcc', 'mean', 12),
    ('lowlevel', 'mfcc', 'mean', 0),
    ('lowlevel', 'mfcc', 'mean', 1),
    ('lowlevel', 'mfcc', 'mean', 2),
    ('lowlevel', 'mfcc', 'mean', 3),
    ('lowlevel', 'mfcc', 'mean', 4),
    ('lowlevel', 'mfcc', 'mean', 5),
    ('lowlevel', 'mfcc', 'mean', 6),
    ('lowlevel', 'mfcc', 'mean', 7),
    ('lowlevel', 'mfcc', 'mean', 8),
    ('lowlevel', 'mfcc', 'mean', 9),
    ('lowlevel', 'mfcc', 'mean', 10),
    ('lowlevel', 'mfcc', 'mean', 11),
    ('lowlevel', 'mfcc', 'mean', 12),
    ('rhythm', 'beats_loudness', 'min'),
    ('rhythm', 'beats_loudness', 'max'),
    ('rhythm', 'beats_loudness', 'median'),
    ('rhythm', 'beats_loudness', 'mean'),
    ('rhythm', 'beats_loudness', 'var'),
    ('rhythm', 'beats_loudness', 'stdev'),
    ('rhythm', 'beats_loudness', 'dmean'),
    ('rhythm', 'beats_loudness', 'dvar'),
    ('rhythm', 'beats_loudness', 'dmean2'),
    ('rhythm', 'beats_loudness', 'dvar2'),
    ('rhythm', 'bpm'),
    ('rhythm', 'bpm_histogram_first_peak_bpm'),
    ('rhythm', 'bpm_histogram_first_peak_weight'),
    ('rhythm', 'bpm_histogram_second_peak_bpm'),
    ('rhythm', 'bpm_histogram_second_peak_weight'),
    ('rhythm', 'danceability'),
    ('rhythm', 'onset_rate'),
    ('rhythm', 'beats_loudness_band_ratio', 'min', 0),
    ('rhythm', 'beats_loudness_band_ratio', 'min', 1),
    ('rhythm', 'beats_loudness_band_ratio', 'min', 2),
    ('rhythm', 'beats_loudness_band_ratio', 'min', 3),
    ('rhythm', 'beats_loudness_band_ratio', 'min', 4),
    ('rhythm', 'beats_loudness_band_ratio', 'min', 5),
    ('rhythm', 'beats_loudness_band_ratio', 'max', 0),
    ('rhythm', 'beats_loudness_band_ratio', 'max', 1),
    ('rhythm', 'beats_loudness_band_ratio', 'max', 2),
    ('rhythm', 'beats_loudness_band_ratio', 'max', 3),
    ('rhythm', 'beats_loudness_band_ratio', 'max', 4),
    ('rhythm', 'beats_loudness_band_ratio', 'max', 5),
    ('rhythm', 'beats_loudness_band_ratio', 'median', 0),
    ('rhythm', 'beats_loudness_band_ratio', 'median', 1),
    ('rhythm', 'beats_loudness_band_ratio', 'median', 2),
    ('rhythm', 'beats_loudness_band_ratio', 'median', 3),
    ('rhythm', 'beats_loudness_band_ratio', 'median', 4),
    ('rhythm', 'beats_loudness_band_ratio', 'median', 5),
    ('rhythm', 'beats_loudness_band_ratio', 'mean', 0),
    ('rhythm', 'beats_loudness_band_ratio', 'mean', 1),
    ('rhythm', 'beats_loudness_band_ratio', 'mean', 2),
    ('rhythm', 'beats_loudness_band_ratio', 'mean', 3),
    ('rhythm', 'beats_loudness_band_ratio', 'mean', 4),
    ('rhythm', 'beats_loudness_band_ratio', 'mean', 5),
    ('rhythm', 'beats_loudness_band_ratio', 'var', 0),
    ('rhythm', 'beats_loudness_band_ratio', 'var', 1),
    ('rhythm', 'beats_loudness_band_ratio', 'var', 2),
    ('rhythm', 'beats_loudness_band_ratio', 'var', 3),
    ('rhythm', 'beats_loudness_band_ratio', 'var', 4),
    ('rhythm', 'beats_loudness_band_ratio', 'var', 5),
    ('rhythm', 'beats_loudness_band_ratio', 'stdev', 0),
    ('rhythm', 'beats_loudness_band_ratio', 'stdev', 1),
    ('rhythm', 'beats_loudness_band_ratio', 'stdev', 2),
    ('rhythm', 'beats_loudness_band_ratio', 'stdev', 3),
    ('rhythm', 'beats_loudness_band_ratio', 'stdev', 4),
    ('rhythm', 'beats_loudness_band_ratio', 'stdev', 5),
    ('rhythm', 'beats_loudness_band_ratio', 'dmean', 0),
    ('rhythm', 'beats_loudness_band_ratio', 'dmean', 1),
    ('rhythm', 'beats_loudness_band_ratio', 'dmean', 2),
    ('rhythm', 'beats_loudness_band_ratio', 'dmean', 3),
    ('rhythm', 'beats_loudness_band_ratio', 'dmean', 4),
    ('rhythm', 'beats_loudness_band_ratio', 'dmean', 5),
    ('rhythm', 'beats_loudness_band_ratio', 'dvar', 0),
    ('rhythm', 'beats_loudness_band_ratio', 'dvar', 1),
    ('rhythm', 'beats_loudness_band_ratio', 'dvar', 2),
    ('rhythm', 'beats_loudness_band_ratio', 'dvar', 3),
    ('rhythm', 'beats_loudness_band_ratio', 'dvar', 4),
    ('rhythm', 'beats_loudness_band_ratio', 'dvar', 5),
    ('rhythm', 'beats_loudness_band_ratio', 'dmean2', 0),
    ('rhythm', 'beats_loudness_band_ratio', 'dmean2', 1),
    ('rhythm', 'beats_loudness_band_ratio', 'dmean2', 2),
    ('rhythm', 'beats_loudness_band_ratio', 'dmean2', 3),
    ('rhythm', 'beats_loudness_band_ratio', 'dmean2', 4),
    ('rhythm', 'beats_loudness_band_ratio', 'dmean2', 5),
    ('rhythm', 'beats_loudness_band_ratio', 'dvar2', 0),
    ('rhythm', 'beats_loudness_band_ratio', 'dvar2', 1),
    ('rhythm', 'beats_loudness_band_ratio', 'dvar2', 2),
    ('rhythm', 'beats_loudness_band_ratio', 'dvar2', 3),
    ('rhythm', 'beats_loudness_band_ratio', 'dvar2', 4),
    ('rhythm', 'beats_loudness_band_ratio', 'dvar2', 5),
    ('tonal', 'chords_changes_rate'),
    ('tonal', 'chords_number_rate'),
    ('tonal', 'chords_strength', 'min'),
    ('tonal', 'chords_strength', 'max'),
    ('tonal', 'chords_strength', 'median'),
    ('tonal', 'chords_strength', 'mean'),
    ('tonal', 'chords_strength', 'var'),
    ('tonal', 'chords_strength', 'stdev'),
    ('tonal', 'chords_strength', 'dmean'),
    ('tonal', 'chords_strength', 'dvar'),
    ('tonal', 'chords_strength', 'dmean2'),
    ('tonal', 'chords_strength', 'dvar2'),
    ('tonal', 'hpcp_crest', 'min'),
    ('tonal', 'hpcp_crest', 'max'),
    ('tonal', 'hpcp_crest', 'median'),
    ('tonal', 'hpcp_crest', 'mean'),
    ('tonal', 'hpcp_crest', 'var'),
    ('tonal', 'hpcp_crest', 'stdev'),
    ('tonal', 'hpcp_crest', 'dmean'),
    ('tonal', 'hpcp_crest', 'dvar'),
    ('tonal', 'hpcp_crest', 'dmean2'),
    ('tonal', 'hpcp_crest', 'dvar2'),
    ('tonal', 'hpcp_entropy', 'min'),
    ('tonal', 'hpcp_entropy', 'max'),
    ('tonal', 'hpcp_entropy', 'median'),
    ('tonal', 'hpcp_entropy', 'mean'),
    ('tonal', 'hpcp_entropy', 'var'),
    ('tonal', 'hpcp_entropy', 'stdev'),
    ('tonal', 'hpcp_entropy', 'dmean'),
    ('tonal', 'hpcp_entropy', 'dvar'),
    ('tonal', 'hpcp_entropy', 'dmean2'),
    ('tonal', 'hpcp_entropy', 'dvar2'),
    ('tonal', 'tuning_diatonic_strength'),
    ('tonal', 'tuning_equal_tempered_deviation'),
    ('tonal', 'tuning_frequency'),
    ('tonal', 'tuning_nontempered_energy_ratio'),
    ('tonal', 'hpcp', 'min', 0),
    ('tonal', 'hpcp', 'min', 1),
    ('tonal', 'hpcp', 'min', 2),
    ('tonal', 'hpcp', 'min', 3),
    ('tonal', 'hpcp', 'min', 4),
    ('tonal', 'hpcp', 'min', 5),
    ('tonal', 'hpcp', 'min', 6),
    ('tonal', 'hpcp', 'min', 7),
    ('tonal', 'hpcp', 'min', 8),
    ('tonal', 'hpcp', 'min', 9),
    ('tonal', 'hpcp', 'min', 10),
    ('tonal', 'hpcp', 'min', 11),
    ('tonal', 'hpcp', 'min', 12),
    ('tonal', 'hpcp', 'min', 13),
    ('tonal', 'hpcp', 'min', 14),
    ('tonal', 'hpcp', 'min', 15),
    ('tonal', 'hpcp', 'min', 16),
    ('tonal', 'hpcp', 'min', 17),
    ('tonal', 'hpcp', 'min', 18),
    ('tonal', 'hpcp', 'min', 19),
    ('tonal', 'hpcp', 'min', 20),
    ('tonal', 'hpcp', 'min', 21),
    ('tonal', 'hpcp', 'min', 22),
    ('tonal', 'hpcp', 'min', 23),
    ('tonal', 'hpcp', 'min', 24),
    ('tonal', 'hpcp', 'min', 25),
    ('tonal', 'hpcp', 'min', 26),
    ('tonal', 'hpcp', 'min', 27),
    ('tonal', 'hpcp', 'min', 28),
    ('tonal', 'hpcp', 'min', 29),
    ('tonal', 'hpcp', 'min', 30),
    ('tonal', 'hpcp', 'min', 31),
    ('tonal', 'hpcp', 'min', 32),
    ('tonal', 'hpcp', 'min', 33),
    ('tonal', 'hpcp', 'min', 34),
    ('tonal', 'hpcp', 'min', 35),
    ('tonal', 'hpcp', 'max', 0),
    ('tonal', 'hpcp', 'max', 1),
    ('tonal', 'hpcp', 'max', 2),
    ('tonal', 'hpcp', 'max', 3),
    ('tonal', 'hpcp', 'max', 4),
    ('tonal', 'hpcp', 'max', 5),
    ('tonal', 'hpcp', 'max', 6),
    ('tonal', 'hpcp', 'max', 7),
    ('tonal', 'hpcp', 'max', 8),
    ('tonal', 'hpcp', 'max', 9),
    ('tonal', 'hpcp', 'max', 10),
    ('tonal', 'hpcp', 'max', 11),
    ('tonal', 'hpcp', 'max', 12),
    ('tonal', 'hpcp', 'max', 13),
    ('tonal', 'hpcp', 'max', 14),
    ('tonal', 'hpcp', 'max', 15),
    ('tonal', 'hpcp', 'max', 16),
    ('tonal', 'hpcp', 'max', 17),
    ('tonal', 'hpcp', 'max', 18),
    ('tonal', 'hpcp', 'max', 19),
    ('tonal', 'hpcp', 'max', 20),
    ('tonal', 'hpcp', 'max', 21),
    ('tonal', 'hpcp', 'max', 22),
    ('tonal', 'hpcp', 'max', 23),
    ('tonal', 'hpcp', 'max', 24),
    ('tonal', 'hpcp', 'max', 25),
    ('tonal', 'hpcp', 'max', 26),
    ('tonal', 'hpcp', 'max', 27),
    ('tonal', 'hpcp', 'max', 28),
    ('tonal', 'hpcp', 'max', 29),
    ('tonal', 'hpcp', 'max', 30),
    ('tonal', 'hpcp', 'max', 31),
    ('tonal', 'hpcp', 'max', 32),
    ('tonal', 'hpcp', 'max', 33),
    ('tonal', 'hpcp', 'max', 34),
    ('tonal', 'hpcp', 'max', 35),
    ('tonal', 'hpcp', 'median', 0),
    ('tonal', 'hpcp', 'median', 1),
    ('tonal', 'hpcp', 'median', 2),
    ('tonal', 'hpcp', 'median', 3),
    ('tonal', 'hpcp', 'median', 4),
    ('tonal', 'hpcp', 'median', 5),
    ('tonal', 'hpcp', 'median', 6),
    ('tonal', 'hpcp', 'median', 7),
    ('tonal', 'hpcp', 'median', 8),
    ('tonal', 'hpcp', 'median', 9),
    ('tonal', 'hpcp', 'median', 10),
    ('tonal', 'hpcp', 'median', 11),
    ('tonal', 'hpcp', 'median', 12),
    ('tonal', 'hpcp', 'median', 13),
    ('tonal', 'hpcp', 'median', 14),
    ('tonal', 'hpcp', 'median', 15),
    ('tonal', 'hpcp', 'median', 16),
    ('tonal', 'hpcp', 'median', 17),
    ('tonal', 'hpcp', 'median', 18),
    ('tonal', 'hpcp', 'median', 19),
    ('tonal', 'hpcp', 'median', 20),
    ('tonal', 'hpcp', 'median', 21),
    ('tonal', 'hpcp', 'median', 22),
    ('tonal', 'hpcp', 'median', 23),
    ('tonal', 'hpcp', 'median', 24),
    ('tonal', 'hpcp', 'median', 25),
    ('tonal', 'hpcp', 'median', 26),
    ('tonal', 'hpcp', 'median', 27),
    ('tonal', 'hpcp', 'median', 28),
    ('tonal', 'hpcp', 'median', 29),
    ('tonal', 'hpcp', 'median', 30),
    ('tonal', 'hpcp', 'median', 31),
    ('tonal', 'hpcp', 'median', 32),
    ('tonal', 'hpcp', 'median', 33),
    ('tonal', 'hpcp', 'median', 34),
    ('tonal', 'hpcp', 'median', 35),
    ('tonal', 'hpcp', 'mean', 0),
    ('tonal', 'hpcp', 'mean', 1),
    ('tonal', 'hpcp', 'mean', 2),
    ('tonal', 'hpcp', 'mean', 3),
    ('tonal', 'hpcp', 'mean', 4),
    ('tonal', 'hpcp', 'mean', 5),
    ('tonal', 'hpcp', 'mean', 6),
    ('tonal', 'hpcp', 'mean', 7),
    ('tonal', 'hpcp', 'mean', 8),
    ('tonal', 'hpcp', 'mean', 9),
    ('tonal', 'hpcp', 'mean', 10),
    ('tonal', 'hpcp', 'mean', 11),
    ('tonal', 'hpcp', 'mean', 12),
    ('tonal', 'hpcp', 'mean', 13),
    ('tonal', 'hpcp', 'mean', 14),
    ('tonal', 'hpcp', 'mean', 15),
    ('tonal', 'hpcp', 'mean', 16),
    ('tonal', 'hpcp', 'mean', 17),
    ('tonal', 'hpcp', 'mean', 18),
    ('tonal', 'hpcp', 'mean', 19),
    ('tonal', 'hpcp', 'mean', 20),
    ('tonal', 'hpcp', 'mean', 21),
    ('tonal', 'hpcp', 'mean', 22),
    ('tonal', 'hpcp', 'mean', 23),
    ('tonal', 'hpcp', 'mean', 24),
    ('tonal', 'hpcp', 'mean', 25),
    ('tonal', 'hpcp', 'mean', 26),
    ('tonal', 'hpcp', 'mean', 27),
    ('tonal', 'hpcp', 'mean', 28),
    ('tonal', 'hpcp', 'mean', 29),
    ('tonal', 'hpcp', 'mean', 30),
    ('tonal', 'hpcp', 'mean', 31),
    ('tonal', 'hpcp', 'mean', 32),
    ('tonal', 'hpcp', 'mean', 33),
    ('tonal', 'hpcp', 'mean', 34),
    ('tonal', 'hpcp', 'mean', 35),
    ('tonal', 'hpcp', 'var', 0),
    ('tonal', 'hpcp', 'var', 1),
    ('tonal', 'hpcp', 'var', 2),
    ('tonal', 'hpcp', 'var', 3),
    ('tonal', 'hpcp', 'var', 4),
    ('tonal', 'hpcp', 'var', 5),
    ('tonal', 'hpcp', 'var', 6),
    ('tonal', 'hpcp', 'var', 7),
    ('tonal', 'hpcp', 'var', 8),
    ('tonal', 'hpcp', 'var', 9),
    ('tonal', 'hpcp', 'var', 10),
    ('tonal', 'hpcp', 'var', 11),
    ('tonal', 'hpcp', 'var', 12),
    ('tonal', 'hpcp', 'var', 13),
    ('tonal', 'hpcp', 'var', 14),
    ('tonal', 'hpcp', 'var', 15),
    ('tonal', 'hpcp', 'var', 16),
    ('tonal', 'hpcp', 'var', 17),
    ('tonal', 'hpcp', 'var', 18),
    ('tonal', 'hpcp', 'var', 19),
    ('tonal', 'hpcp', 'var', 20),
    ('tonal', 'hpcp', 'var', 21),
    ('tonal', 'hpcp', 'var', 22),
    ('tonal', 'hpcp', 'var', 23),
    ('tonal', 'hpcp', 'var', 24),
    ('tonal', 'hpcp', 'var', 25),
    ('tonal', 'hpcp', 'var', 26),
    ('tonal', 'hpcp', 'var', 27),
    ('tonal', 'hpcp', 'var', 28),
    ('tonal', 'hpcp', 'var', 29),
    ('tonal', 'hpcp', 'var', 30),
    ('tonal', 'hpcp', 'var', 31),
    ('tonal', 'hpcp', 'var', 32),
    ('tonal', 'hpcp', 'var', 33),
    ('tonal', 'hpcp', 'var', 34),
    ('tonal', 'hpcp', 'var', 35),
    ('tonal', 'hpcp', 'stdev', 0),
    ('tonal', 'hpcp', 'stdev', 1),
    ('tonal', 'hpcp', 'stdev', 2),
    ('tonal', 'hpcp', 'stdev', 3),
    ('tonal', 'hpcp', 'stdev', 4),
    ('tonal', 'hpcp', 'stdev', 5),
    ('tonal', 'hpcp', 'stdev', 6),
    ('tonal', 'hpcp', 'stdev', 7),
    ('tonal', 'hpcp', 'stdev', 8),
    ('tonal', 'hpcp', 'stdev', 9),
    ('tonal', 'hpcp', 'stdev', 10),
    ('tonal', 'hpcp', 'stdev', 11),
    ('tonal', 'hpcp', 'stdev', 12),
    ('tonal', 'hpcp', 'stdev', 13),
    ('tonal', 'hpcp', 'stdev', 14),
    ('tonal', 'hpcp', 'stdev', 15),
    ('tonal', 'hpcp', 'stdev', 16),
    ('tonal', 'hpcp', 'stdev', 17),
    ('tonal', 'hpcp', 'stdev', 18),
    ('tonal', 'hpcp', 'stdev', 19),
    ('tonal', 'hpcp', 'stdev', 20),
    ('tonal', 'hpcp', 'stdev', 21),
    ('tonal', 'hpcp', 'stdev', 22),
    ('tonal', 'hpcp', 'stdev', 23),
    ('tonal', 'hpcp', 'stdev', 24),
    ('tonal', 'hpcp', 'stdev', 25),
    ('tonal', 'hpcp', 'stdev', 26),
    ('tonal', 'hpcp', 'stdev', 27),
    ('tonal', 'hpcp', 'stdev', 28),
    ('tonal', 'hpcp', 'stdev', 29),
    ('tonal', 'hpcp', 'stdev', 30),
    ('tonal', 'hpcp', 'stdev', 31),
    ('tonal', 'hpcp', 'stdev', 32),
    ('tonal', 'hpcp', 'stdev', 33),
    ('tonal', 'hpcp', 'stdev', 34),
    ('tonal', 'hpcp', 'stdev', 35),
    ('tonal', 'hpcp', 'dmean', 0),
    ('tonal', 'hpcp', 'dmean', 1),
    ('tonal', 'hpcp', 'dmean', 2),
    ('tonal', 'hpcp', 'dmean', 3),
    ('tonal', 'hpcp', 'dmean', 4),
    ('tonal', 'hpcp', 'dmean', 5),
    ('tonal', 'hpcp', 'dmean', 6),
    ('tonal', 'hpcp', 'dmean', 7),
    ('tonal', 'hpcp', 'dmean', 8),
    ('tonal', 'hpcp', 'dmean', 9),
    ('tonal', 'hpcp', 'dmean', 10),
    ('tonal', 'hpcp', 'dmean', 11),
    ('tonal', 'hpcp', 'dmean', 12),
    ('tonal', 'hpcp', 'dmean', 13),
    ('tonal', 'hpcp', 'dmean', 14),
    ('tonal', 'hpcp', 'dmean', 15),
    ('tonal', 'hpcp', 'dmean', 16),
    ('tonal', 'hpcp', 'dmean', 17),
    ('tonal', 'hpcp', 'dmean', 18),
    ('tonal', 'hpcp', 'dmean', 19),
    ('tonal', 'hpcp', 'dmean', 20),
    ('tonal', 'hpcp', 'dmean', 21),
    ('tonal', 'hpcp', 'dmean', 22),
    ('tonal', 'hpcp', 'dmean', 23),
    ('tonal', 'hpcp', 'dmean', 24),
    ('tonal', 'hpcp', 'dmean', 25),
    ('tonal', 'hpcp', 'dmean', 26),
    ('tonal', 'hpcp', 'dmean', 27),
    ('tonal', 'hpcp', 'dmean', 28),
    ('tonal', 'hpcp', 'dmean', 29),
    ('tonal', 'hpcp', 'dmean', 30),
    ('tonal', 'hpcp', 'dmean', 31),
    ('tonal', 'hpcp', 'dmean', 32),
    ('tonal', 'hpcp', 'dmean', 33),
    ('tonal', 'hpcp', 'dmean', 34),
    ('tonal', 'hpcp', 'dmean', 35),
    ('tonal', 'hpcp', 'dvar', 0),
    ('tonal', 'hpcp', 'dvar', 1),
    ('tonal', 'hpcp', 'dvar', 2),
    ('tonal', 'hpcp', 'dvar', 3),
    ('tonal', 'hpcp', 'dvar', 4),
    ('tonal', 'hpcp', 'dvar', 5),
    ('tonal', 'hpcp', 'dvar', 6),
    ('tonal', 'hpcp', 'dvar', 7),
    ('tonal', 'hpcp', 'dvar', 8),
    ('tonal', 'hpcp', 'dvar', 9),
    ('tonal', 'hpcp', 'dvar', 10),
    ('tonal', 'hpcp', 'dvar', 11),
    ('tonal', 'hpcp', 'dvar', 12),
    ('tonal', 'hpcp', 'dvar', 13),
    ('tonal', 'hpcp', 'dvar', 14),
    ('tonal', 'hpcp', 'dvar', 15),
    ('tonal', 'hpcp', 'dvar', 16),
    ('tonal', 'hpcp', 'dvar', 17),
    ('tonal', 'hpcp', 'dvar', 18),
    ('tonal', 'hpcp', 'dvar', 19),
    ('tonal', 'hpcp', 'dvar', 20),
    ('tonal', 'hpcp', 'dvar', 21),
    ('tonal', 'hpcp', 'dvar', 22),
    ('tonal', 'hpcp', 'dvar', 23),
    ('tonal', 'hpcp', 'dvar', 24),
    ('tonal', 'hpcp', 'dvar', 25),
    ('tonal', 'hpcp', 'dvar', 26),
    ('tonal', 'hpcp', 'dvar', 27),
    ('tonal', 'hpcp', 'dvar', 28),
    ('tonal', 'hpcp', 'dvar', 29),
    ('tonal', 'hpcp', 'dvar', 30),
    ('tonal', 'hpcp', 'dvar', 31),
    ('tonal', 'hpcp', 'dvar', 32),
    ('tonal', 'hpcp', 'dvar', 33),
    ('tonal', 'hpcp', 'dvar', 34),
    ('tonal', 'hpcp', 'dvar', 35),
    ('tonal', 'hpcp', 'dmean2', 0),
    ('tonal', 'hpcp', 'dmean2', 1),
    ('tonal', 'hpcp', 'dmean2', 2),
    ('tonal', 'hpcp', 'dmean2', 3),
    ('tonal', 'hpcp', 'dmean2', 4),
    ('tonal', 'hpcp', 'dmean2', 5),
    ('tonal', 'hpcp', 'dmean2', 6),
    ('tonal', 'hpcp', 'dmean2', 7),
    ('tonal', 'hpcp', 'dmean2', 8),
    ('tonal', 'hpcp', 'dmean2', 9),
    ('tonal', 'hpcp', 'dmean2', 10),
    ('tonal', 'hpcp', 'dmean2', 11),
    ('tonal', 'hpcp', 'dmean2', 12),
    ('tonal', 'hpcp', 'dmean2', 13),
    ('tonal', 'hpcp', 'dmean2', 14),
    ('tonal', 'hpcp', 'dmean2', 15),
    ('tonal', 'hpcp', 'dmean2', 16),
    ('tonal', 'hpcp', 'dmean2', 17),
    ('tonal', 'hpcp', 'dmean2', 18),
    ('tonal', 'hpcp', 'dmean2', 19),
    ('tonal', 'hpcp', 'dmean2', 20),
    ('tonal', 'hpcp', 'dmean2', 21),
    ('tonal', 'hpcp', 'dmean2', 22),
    ('tonal', 'hpcp', 'dmean2', 23),
    ('tonal', 'hpcp', 'dmean2', 24),
    ('tonal', 'hpcp', 'dmean2', 25),
    ('tonal', 'hpcp', 'dmean2', 26),
    ('tonal', 'hpcp', 'dmean2', 27),
    ('tonal', 'hpcp', 'dmean2', 28),
    ('tonal', 'hpcp', 'dmean2', 29),
    ('tonal', 'hpcp', 'dmean2', 30),
    ('tonal', 'hpcp', 'dmean2', 31),
    ('tonal', 'hpcp', 'dmean2', 32),
    ('tonal', 'hpcp', 'dmean2', 33),
    ('tonal', 'hpcp', 'dmean2', 34),
    ('tonal', 'hpcp', 'dmean2', 35),
    ('tonal', 'hpcp', 'dvar2', 0),
    ('tonal', 'hpcp', 'dvar2', 1),
    ('tonal', 'hpcp', 'dvar2', 2),
    ('tonal', 'hpcp', 'dvar2', 3),
    ('tonal', 'hpcp', 'dvar2', 4),
    ('tonal', 'hpcp', 'dvar2', 5),
    ('tonal', 'hpcp', 'dvar2', 6),
    ('tonal', 'hpcp', 'dvar2', 7),
    ('tonal', 'hpcp', 'dvar2', 8),
    ('tonal', 'hpcp', 'dvar2', 9),
    ('tonal', 'hpcp', 'dvar2', 10),
    ('tonal', 'hpcp', 'dvar2', 11),
    ('tonal', 'hpcp', 'dvar2', 12),
    ('tonal', 'hpcp', 'dvar2', 13),
    ('tonal', 'hpcp', 'dvar2', 14),
    ('tonal', 'hpcp', 'dvar2', 15),
    ('tonal', 'hpcp', 'dvar2', 16),
    ('tonal', 'hpcp', 'dvar2', 17),
    ('tonal', 'hpcp', 'dvar2', 18),
    ('tonal', 'hpcp', 'dvar2', 19),
    ('tonal', 'hpcp', 'dvar2', 20),
    ('tonal', 'hpcp', 'dvar2', 21),
    ('tonal', 'hpcp', 'dvar2', 22),
    ('tonal', 'hpcp', 'dvar2', 23),
    ('tonal', 'hpcp', 'dvar2', 24),
    ('tonal', 'hpcp', 'dvar2', 25),
    ('tonal', 'hpcp', 'dvar2', 26),
    ('tonal', 'hpcp', 'dvar2', 27),
    ('tonal', 'hpcp', 'dvar2', 28),
    ('tonal', 'hpcp', 'dvar2', 29),
    ('tonal', 'hpcp', 'dvar2', 30),
    ('tonal', 'hpcp', 'dvar2', 31),
    ('tonal', 'hpcp', 'dvar2', 32),
    ('tonal', 'hpcp', 'dvar2', 33),
    ('tonal', 'hpcp', 'dvar2', 34),
    ('tonal', 'hpcp', 'dvar2', 35),
    ('tonal', 'chords_histogram', 0),
    ('tonal', 'chords_histogram', 1),
    ('tonal', 'chords_histogram', 2),
    ('tonal', 'chords_histogram', 3),
    ('tonal', 'chords_histogram', 4),
    ('tonal', 'chords_histogram', 5),
    ('tonal', 'chords_histogram', 6),
    ('tonal', 'chords_histogram', 7),
    ('tonal', 'chords_histogram', 8),
    ('tonal', 'chords_histogram', 9),
    ('tonal', 'chords_histogram', 10),
    ('tonal', 'chords_histogram', 11),
    ('tonal', 'chords_histogram', 12),
    ('tonal', 'chords_histogram', 13),
    ('tonal', 'chords_histogram', 14),
    ('tonal', 'chords_histogram', 15),
    ('tonal', 'chords_histogram', 16),
    ('tonal', 'chords_histogram', 17),
    ('tonal', 'chords_histogram', 18),
    ('tonal', 'chords_histogram', 19),
    ('tonal', 'chords_histogram', 20),
    ('tonal', 'chords_histogram', 21),
    ('tonal', 'chords_histogram', 22),
    ('tonal', 'chords_histogram', 23),
    ('tonal', 'thpcp', 0),
    ('tonal', 'thpcp', 1),
    ('tonal', 'thpcp', 2),
    ('tonal', 'thpcp', 3),
    ('tonal', 'thpcp', 4),
    ('tonal', 'thpcp', 5),
    ('tonal', 'thpcp', 6),
    ('tonal', 'thpcp', 7),
    ('tonal', 'thpcp', 8),
    ('tonal', 'thpcp', 9),
    ('tonal', 'thpcp', 10),
    ('tonal', 'thpcp', 11),
    ('tonal', 'thpcp', 12),
    ('tonal', 'thpcp', 13),
    ('tonal', 'thpcp', 14),
    ('tonal', 'thpcp', 15),
    ('tonal', 'thpcp', 16),
    ('tonal', 'thpcp', 17),
    ('tonal', 'thpcp', 18),
    ('tonal', 'thpcp', 19),
    ('tonal', 'thpcp', 20),
    ('tonal', 'thpcp', 21),
    ('tonal', 'thpcp', 22),
    ('tonal', 'thpcp', 23),
    ('tonal', 'thpcp', 24),
    ('tonal', 'thpcp', 25),
    ('tonal', 'thpcp', 26),
    ('tonal', 'thpcp', 27),
    ('tonal', 'thpcp', 28),
    ('tonal', 'thpcp', 29),
    ('tonal', 'thpcp', 30),
    ('tonal', 'thpcp', 31),
    ('tonal', 'thpcp', 32),
    ('tonal', 'thpcp', 33),
    ('tonal', 'thpcp', 34),
    ('tonal', 'thpcp', 35),
]


_feature_names = []


def names():
    global _feature_paths
    global _feature_names
    if len(_feature_paths) != len(_feature_names):
        # Concatenate the path to each feature for use as its name.
        _feature_names = [".".join(str(f) for f in p) for p in _feature_paths]
        # Trim off the leading component, since we believe names should be
        # unique even without the top level namespace - it just adds noise.
        _feature_names = [s.split('.', 1)[-1] for s in _feature_names]
    return _feature_names


# Some notes about normalization.
"""
average_loudness: 0..1
beats_loudness: 0..1.02, mean=0.09, std=0.07
beats_loudness_band_ratio: 0..1
bpm: 70..185, mean=124.1, std=16.18
chord_changes_rate: 9.263E-3..0.15, mean=0.06, std=0.02
chords_histogram: 0..92
chords_number_rate: 1.674E-4..0.02, mean=1.247E-3, std=7.681E-4
chords_strength: -1..1, mean=0.53, std=0.11
danceability: 0.76..2.38, mean=1.38, std=0.22
dissonance: 0..5, mean=0.46, std=0.04
dynamic_complexity: 1.64..12.79, mean=4.07, std=1.01
hfc: 0..2454, mean=24.64, std=36.02
hpcp_crest: 0..36, mean=12.72, std=6.21
hpcp_entropy: 0..5.14, mean=2.17, std=0.80
onset_rate: 2.44..8.09, mean=5.00, std=0.83 (onsets per second)
pitch_salience: 0..1, mean=0.44, std=0.21
silence_rate_20dB: 0..1, mean=0.99, std=0.03
silence_rate_30dB: 0..1, mean=0.78, std=0.37
silence_rate_60dB: 0..1, mean=0.12, std=0.31
tuning_diatonic_strength: 0.20..0.81, mean=0.59, std=0.07
tuning_equal_tempered_deviation: 0.01..0.46, mean=0.20, std=0.06
tuning_frequency: 431.2Hz..456.6Hz, mean=435.2Hz, std=3.09Hz
tuning_nontempered_energy_ratio: 0.59..1.0, mean=0.89, std=0.06
zerocrossingrate: 0..1, mean=0.05, std=0.06


gfcc.mean: -227.9..224.7
mfcc.mean: -869.6..601.8
hpcp: 0..1
thpcp: 0..1

spectral:
    _centroid: 12.15..15440, mean=1187, std=842.2 (Hz)
    _complexity: 0..88, mean=14.19, std=10.79
        number of peaks in the spectrum; theoretical max N_FFT/2 == 2048
    _contrast_coeffs: -1.00..-0.15, mean=-0.8, std=0.08
    _contrast_valleys: -28.55..-3.59, mean=-8, std=1.5
    _decrease: -3.242E-7..7.757E-9, mean=1.586E-8, std=1.646E-8
    _energy: 0..1.23, mean=0.06, std=0.06
    _energyband_high: 0..0.26, mean=1.502E-3, std=3.287E-3
    _energyband_low: 0..1.22, mean=0.05, std=0.06
    _energyband_middle_high: 0..0.35, mean=3.502E-3, std=5.306E-3
    _energyband_middle_low: 0..0.57, mean=9.768E-3, 0.01
    _entropy: 1.88..10.0, mean=7.36, std=0.82
    _flux: 0..0.92, mean=0.11, std=0.09
    _kurtosis: -2..3778, mean=13.02, std=29.52
    _rms: 0..0.03
    _rolloff: 21.53..22050, mean=1433, std=2336
    _skewness: -5.25..48.75, mean=2.14, std=1.61
    _spread: 2.717E+4..5.341E+7, mean=5.181E+6, std=2.707E+6
    _strongpeak: 0..107.8, mean=0.70, std=0.80

With 27 barkbands:
    _crest: 1..27
    _flatness_db: 0..1
    _kurtosis: -2 : 1.413E+5, mean=50, std=1.727E+2
    _skewness: -95.91..247.7, mean=3.51, std=4.13
    _spread: 1.274E-3 : 1.686E+2, mean=17.77, std=17.91

With 40 erbbands:
    _crest: 1.50..35.77
    _flatness_db: 0..0.85, mean=0.17, std=0.08
    _kurtosis: -2 : 1.219E+3, mean=3.21, std=12.81
    _skewness: -30.13..22.14, mean=0.57, std=1.31
    _spread: 0.16..285.7, mean=43.64, std=29.36

loudness_ebu128, all in dB:
    .integrated: -16.55..-2.97, mean=-9.19, std=1.52
    .loudness_range: 1.27..21.63, mean=6.76, std=2.85
    .momentary: -3.008E+2..-0.87, mean=-11.35, std=8.20
    .short_term: -3.007E+2..-1.57, mean=-10.67, std=5.25

With 40 mel bands:
    _crest: 1.00..40.00
    _flatness_db: 0..1, mean=0.30, std=0.15
    _kurtosis: -2.00..1.399E+8, mean=6.224E+2, std=6.562E+3
    _skewness: -24.54..1.143E+4, mean=4.95, std=5.18
    _spread: 0..353.1, mean=17.61, std=22.38


"""


def _follow(obj, key, *args):
    # Dig into a JSON object and follow the key path, returning the value
    # when we reach the end of the path.
    val = obj[key]
    return _follow(val, *args) if len(args) else val


def extract(details, track):
    # Extract the features we care about from the Essentia json object.
    # Save them into a Numpy array. Write that array to the 'features' path.
    array = np.zeros(len(_feature_paths), dtype=np.float)
    for i, path in enumerate(_feature_paths):
        array[i] = _follow(details, *path)
    np.save(track.features_file, array)


def check(track):
    if not os.path.isfile(track.features_file):
        return False
    try:
        data = np.load(track.features_file)
        return data.shape == (len(_feature_paths),)
    except IOError as e:
        return False


def generate(track):
    with open(track.details_file, 'r') as fd:
        extract(json.load(fd, strict=False), track)


def matrix(tracks):
    # returns an array with shape [tracks, features]
    empty = np.zeros(len(_feature_paths), dtype=np.float)
    files = (t.features_file for t in tracks)
    feats = [(np.load(f) if os.path.isfile(f) else empty) for f in files]
    return np.array(feats)


def normalize(matrix):
    # accepts an array with shape [tracks, features], normalizes, returns it
    # Scale the limits so that all values fall within 0..1 for each feature.
    # If the min and max are equal, leave the value set at zero.
    scaled = matrix.copy()
    scaled -= scaled.min(axis=0)
    maxv = scaled.max(axis=0)
    scaled[:,maxv.nonzero()] /= maxv[maxv.nonzero()]
    # Compute the linear average, then get the logarithm in that base of the
    # value 0.5. We will correct for distribution nonlinearity by raising every
    # scaled value to this power.
    meanv = scaled.mean(axis=0)
    powers = np.ones_like(meanv)
    powers[meanv.nonzero()] = np.log(0.5) / np.log(meanv[meanv.nonzero()])
    curved = scaled ** powers
    return curved


if __name__ == '__main__':
    print("Saved features array schema:")
    for i, name in enumerate(_feature_names):
        print("    %d: '%s'" % (i, name))
    print("Total features: %d" % len(_feature_names))
